import './globals.css'
import type { Metadata } from 'next'
import { Inter, Josefin_Sans } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })
const josefin_Sans = Josefin_Sans({ 
  subsets: ['latin'],
weight: ['400', '600'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${josefin_Sans.className}`}>{children}</body>
    </html>
  )
}
